### Add new product
POST http://localhost:2000/api/v1/products
Content-Type: application/json

{
  "name": "Galaxy S22 - Black",
  "sku": "GAL-001-2700-Gre",
  "category": 1,
  "description": "Galaxy S21-FE of black color",
  "large_description": "Galaxy S21-FE of black color, 256GB of memory and 8GB of RAM.",
  "price": 2700,
  "discount_percent": 0.5,
  "discount_price": 1350
}



### Update product
PATCH http://localhost:2000/api/v1/products/4
Content-Type: application/json

{
  "name": "Galaxy A55 - Black"
}



### Get all products
GET http://localhost:2000/api/v1/products?page=1&perPage=4&order=desc



### Get special products
GET http://localhost:2000/api/v1/products/special?page=1&perPage=2&order=desc



### Delete product
Delete http://localhost:2000/api/v1/products/8
