### Add new category
POST http://localhost:2000/api/v1/category
Content-Type: application/json

{
  "name": "Cama, mesa e banho",
  "image_link": "https://images.com/img.png"
}


### Add many categories
POST http://localhost:2000/api/v1/category/many
Content-Type: application/json

{
  "categories": [
    {
      "name": "Dining",
      "image_link": "https://i.postimg.cc/XNcsnjHC/jantar.png"
    },
    {
      "name": "Living",
      "image_link": "https://i.postimg.cc/Xq3x9mJq/sala.png"
    },
    {
      "name": "Bedroom",
      "image_link": "https://i.postimg.cc/MTJY8N15/quarto.png"
    }
  ]
}


### Get all categories
GET http://localhost:2000/api/v1/category

